import { Component } from '@angular/core';

@Component({
  selector: 'app-auto-generated',
  templateUrl: './auto-generated.component.html',
  styleUrls: ['./auto-generated.component.css']
})
export class AutoGeneratedComponent {

  constructor() { }

  public accelerometerData;

  public startAccelerometer() {
    const accelerometer = require('nativescript-accelerometer');
    alert('start');
    accelerometer.startAccelerometerUpdates((data) => {
      console.log(data);
      this.accelerometerData = data;
    }, { sensorDelay: 'ui' });
  }
}
