import { Component } from '@angular/core';
import { registerElement } from 'nativescript-angular/element-registry';
import { CanvasView, Paint, createRect, Canvas } from 'nativescript-canvas';
import { Color } from 'tns-core-modules/color/color';

@Component({
  selector: 'app-auto-generated',
  templateUrl: './auto-generated.component.html',
  styleUrls: ['./auto-generated.component.css']
})
export class AutoGeneratedComponent {

  constructor() {
    registerElement('CanvasView', () => CanvasView);
   }

  public accelerometerData;
  public canvasEvent;

  public startAccelerometer() {
    const accelerometer = require('nativescript-accelerometer');
    console.log('start');
    accelerometer.startAccelerometerUpdates((data) => {
      this.accelerometerData = data;
      this.draw();
    }, { sensorDelay: 'ui' });
  }

  public drawInit(event: { canvas: Canvas }) {
    this.canvasEvent = event.canvas;
    const paint = new Paint();
    paint.setColor(new Color('black'));
    paint.strokeWidth = 10;
    event.canvas.drawCircle(0, 0, 10, paint);
  }

  private draw() {
    const canvas = new Canvas(100, 200);
    const paint = new Paint();
    paint.setColor(new Color('black'));
    paint.strokeWidth = 10;
    canvas.drawRect(createRect(0, 0, this.accelerometerData.x * 100, this.accelerometerData.y * 100), paint);
  }
}
