import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { AutoGeneratedComponent } from './auto-generated/auto-generated.component';

const routes: Routes = [
  { path:'', component: AutoGeneratedComponent}
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
